In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]


In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_list

[1, 2, 3]

In [8]:
myarr = np.array(my_list)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [27]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [29]:
len(np.linspace(0,5,21))

21

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(1)

array([0.21063353])

In [33]:
np.random.rand(5,6)

array([[0.00153104, 0.10877898, 0.31485589, 0.92257137, 0.20504399,
        0.02268634],
       [0.15514427, 0.48384369, 0.05283676, 0.8451773 , 0.2771535 ,
        0.07550976],
       [0.51728351, 0.07580977, 0.90773616, 0.33744983, 0.183123  ,
        0.21580555],
       [0.85875684, 0.70726757, 0.31440159, 0.65442039, 0.16884409,
        0.52936809],
       [0.55014335, 0.11954053, 0.13379956, 0.19391375, 0.06949336,
        0.99479256]])

In [34]:
np.random.rand(5,2)

array([[0.35529479, 0.70521601],
       [0.64268173, 0.87720496],
       [0.57421114, 0.31336628],
       [0.75090538, 0.15312682],
       [0.10397507, 0.00466198]])

In [35]:
np.random.randn(10)

array([-0.77934215, -1.16327784, -0.86509259, -0.4368529 ,  0.37937978,
        0.93948251, -1.08149035, -0.64600163, -0.25296053, -0.57772026])

In [36]:
np.random.randn(2,3)

array([[ 0.59985102, -0.45951428, -0.18516882],
       [ 0.64983856, -1.32477747,  1.19784816]])

In [37]:
np.random.randint(0,101,5)

array([91, 85, 54, 53, 50])

In [38]:
np.random.randint(0,101,(4,5))

array([[64, 71, 91, 92, 64],
       [10, 14, 74, 49, 42],
       [50, 47, 41, 65, 82],
       [40, 27, 88, 69, 50]])

In [39]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [40]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [41]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [42]:
np.random.seed(101)

In [44]:
arr = np.arange(0,25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr = np.random.randint(0,101,10)

In [48]:
ranarr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [49]:
ranarr.max()

95

In [50]:
ranarr.min()

9

In [51]:
ranarr.argmax()

0

In [52]:
ranarr.argmin()

7

In [53]:
ranarr.dtype

dtype('int32')

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr.shape

(25,)

In [57]:
arr = arr.reshape(5,5)

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr.shape

(5, 5)

In [60]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [61]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])